<a href="https://colab.research.google.com/github/khiemchuong/baitaptailop/blob/main/BTVN_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
import numpy as np
_a=[5,4,3,6,2,9,7]
a=np.array(_a)
print(a)

[5 4 3 6 2 9 7]


In [ ]:
#2
import random
b=[random.randint(-10,10) for i in range(0,30)]
print(b)


[-6, -4, -7, -5, 7, -6, 2, 4, 9, -9, 9, -9, 10, -10, 10, 1, -4, -7, 2, 6, 8, -2, 4, -10, 5, -7, -1, 0, -1, 10]


In [ ]:
#3
import numpy as np
c=[-5,7,6,9]
e=np.random.choice(c, size=(30,))
print(e)



[ 6  7  7  6 -5  9  6 -5  6 -5 -5  6  9 -5  7  7 -5  9  6  7  9 -5  7  6
  6  7 -5 -5  7 -5]


In [ ]:
#4 
import numpy as np
import random
x=int(input('x='))
_r=[random.randint(1,20) for i in range(0,10)]
r=np.array(_r)
print(r)

print('r*x:',r*x)


x=4
[16 14 19  1 17  8 12  9 13 10]
r*x: [64 56 76  4 68 32 48 36 52 40]


In [ ]:
#5
import numpy as np 
import random
_z=[random.randint(1,20) for i in range(0,15)]
_x=[random.randint(1,20) for i in range(0,15)]
z=np.array(_z)
x=np.array(_x)
print(z)
print(x)
print('x+z:',x+z)
print('x-z:',x-z)

[ 6 16 15  2 11 15  6 11 14 16 16  1  6 18 10]
[17 19  6  4 12 12  1  7 10 10 18 10 17  6 18]
x+z: [23 35 21  6 23 27  7 18 24 26 34 11 23 24 28]
x-z: [ 11   3  -9   2   1  -3  -5  -4  -4  -6   2   9  11 -12   8]


In [ ]:
#6
import numpy as np
import random
_v=[random.randint(1,20) for i in range(0,10)]
_n=[random.randint(1,20) for i in range(0,10)]
v=np.array(_v)
n=np.array(_n)
print(v)
print(n)
print('v*n',v*n)

[ 6  2  1  8  9 17  2 20  1 10]
[ 6 12  9 16 13 13 20  4  9 15]
v*n [ 36  24   9 128 117 221  40  80   9 150]


In [ ]:
#7
import numpy as np
import random
from math import cos
_m=[random.randint(1,20) for i in range(0,10)]
_s=[random.randint(1,20) for i in range(0,10)]
p=abs(int(input('p=')))
i=0
m=np.array(_m)
s=np.array(_s)
print(m)
print(s)
for i in range(1,p-1):
  f=s*m


print('f:',f)

p=5
[ 7 16  3  1  9  3  5  4 15  6]
[13 16  7 13  6 11  3 10 12  7]
f: [ 91 256  21  13  54  33  15  40 180  42]


In [ ]:
#8
import numpy as np
j=np.random.randint(0,5,size = (3,5))
print('j:',j)
print('j[2,3]:',j[2,3])

j: [[1 2 0 2 3]
 [1 4 2 2 3]
 [0 2 4 0 3]]
j[2,3]: 0


In [ ]:
#9
import numpy as np
g=np.random.randint(0,5,size = (3,5))
h=abs(int(input('h=')))
print(g)
print('g*h:',g*h)

h=5
[[0 4 0 3 4]
 [1 4 3 2 4]
 [0 3 4 3 3]]
g*h: [[ 0 20  0 15 20]
 [ 5 20 15 10 20]
 [ 0 15 20 15 15]]


In [ ]:
#10
import numpy as np 
k=np.random.randint(0,5,size = (3,5))
print('k:',k)
l=np.random.randint(0,5,size = (3,5))
print('l:',l)
print('k+l:',k+l)

k: [[1 3 3 0 4]
 [4 2 3 0 1]
 [2 2 3 2 3]]
l: [[3 0 3 4 4]
 [2 0 2 1 2]
 [1 1 1 1 0]]
k+l: [[4 3 6 4 8]
 [6 2 5 1 3]
 [3 3 4 3 3]]


In [ ]:
#11
import numpy as np
q=np.random.randint(0,5,size = (3,4))
print('q:',q)
w=np.random.randint(0,5,size = (4,5))
print('w:',w)

r=q.dot(w)
print('r:',r)

q: [[0 2 2 4]
 [0 4 1 4]
 [2 2 3 2]]
w: [[3 4 3 0 3]
 [0 3 3 2 4]
 [0 1 1 1 4]
 [2 0 1 3 4]]
r: [[ 8  8 12 18 32]
 [ 8 13 17 21 36]
 [10 17 17 13 34]]
